# Generated by Django 5.0.10 on 2026-04-29 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='예: T1·1', max_length=8, unique=True)),
                ('tier', models.CharField(choices=[('T1', 'T1. 수강생 케어·운영'), ('T2', 'T2. 콘텐츠·지식 인프라'), ('T3', 'T3. 업무·행정·CS')], max_length=2)),
                ('num', models.IntegerField(help_text='카테고리 번호 (1~8)')),
                ('title', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text='엑셀 원본 행 번호 (R2~R47)', unique=True)),
                ('title', models.CharField(help_text='엑셀 한줄요약', max_length=300)),
                ('description', models.TextField(help_text='엑셀 AI 청사진')),
                ('proposer', models.CharField(help_text='제안자 이름', max_length=100)),
                ('proposer_email', models.EmailField(blank=True, help_text='제안자 이메일 (PII, 비표시)', max_length=254)),
                ('division', models.CharField(default='교육운영실', max_length=50)),
                ('org', models.CharField(blank=True, help_text="엑셀 '조직' 컬럼 원문", max_length=100)),
                ('impact_scope', models.CharField(blank=True, help_text='영향범위', max_length=100)),
                ('manual_minutes', models.IntegerField(blank=True, help_text='수동 소요시간 (1회/분)', null=True)),
                ('monthly_uses', models.IntegerField(blank=True, help_text='월 사용횟수', null=True)),
                ('priority', models.CharField(choices=[('P0', 'P0 (지금 반복하는 일의 시간을 확실히 줄여줌)'), ('P1', 'P1 (시간을 줄여주긴 하나 효과가 상대적으로 작음)'), ('P2', 'P2 (시간 절약보다는 업무 품질 개선에 가까움)'), ('P3', 'P3 (기존 업무 외 새로운 업무 제안/아이디어)'), ('unset', '(미지정)')], default='unset', max_length=10)),
                ('difficulty', models.CharField(choices=[('low', '낮음'), ('mid', '중간'), ('high', '높음'), ('unset', '(미평가)')], default='unset', max_length=10)),
                ('deploy_intent', models.BooleanField(default=False, help_text='전체 배포 의도')),
                ('stage', models.IntegerField(choices=[(1, '1단계 (담당자 직접 진행)'), (2, '2단계 (인솔파 위임 후보)'), (3, '3단계 (인솔파 직접 위임)')], default=1)),
                ('status', models.CharField(choices=[('not_started', '시작 전'), ('in_progress', '진행 중'), ('done', '완료'), ('archived', '보관')], default='not_started', max_length=20)),
                ('result_url', models.URLField(blank=True)),
                ('name_public', models.BooleanField(default=True, help_text='제안자 이름 공개 동의. False 면 이니셜만 노출')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='catalog.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카탈로그 항목',
                'verbose_name_plural': '카탈로그 항목',
                'ordering': ['source_id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('low', '낮음'), ('mid', '중간'), ('high', '높음'), ('unset', '(미평가)')], max_length=10)),
                ('est_effort_days', models.IntegerField(blank=True, help_text='예상 공수 (일)', null=True)),
                ('deploy_intent', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='catalog.project')),
            ],
            options={
                'verbose_name': '기술 난이도 평가',
                'verbose_name_plural': '기술 난이도 평가',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.IntegerField(blank=True, choices=[(1, '1단계 (담당자 직접 진행)'), (2, '2단계 (인솔파 위임 후보)'), (3, '3단계 (인솔파 직접 위임)')], null=True)),
                ('to_stage', models.IntegerField(choices=[(1, '1단계 (담당자 직접 진행)'), (2, '2단계 (인솔파 위임 후보)'), (3, '3단계 (인솔파 직접 위임)')])),
                ('reason', models.TextField(blank=True)),
                ('actor_label', models.CharField(blank=True, help_text="actor FK 없을 때 fallback (예: '주인', 'import-script')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_transitions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='catalog.project')),
            ],
            options={
                'verbose_name': '단계 변동 이력',
                'verbose_name_plural': '단계 변동 이력',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['stage'], name='catalog_pro_stage_d36230_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'stage'], name='catalog_pro_categor_712a47_idx'),
        ),
    ]
