# Generated by Django 5.0.10 on 2026-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.IntegerField(choices=[(1, '1단계 (담당자 직접 진행)'), (2, '2단계 (인솔파 위임 후보)'), (3, '3단계 (인솔파 직접 위임)'), (4, '기타 (제외·별도 관리)')], default=1),
        ),
        migrations.AlterField(
            model_name='stagetransition',
            name='from_stage',
            field=models.IntegerField(blank=True, choices=[(1, '1단계 (담당자 직접 진행)'), (2, '2단계 (인솔파 위임 후보)'), (3, '3단계 (인솔파 직접 위임)'), (4, '기타 (제외·별도 관리)')], null=True),
        ),
        migrations.AlterField(
            model_name='stagetransition',
            name='to_stage',
            field=models.IntegerField(choices=[(1, '1단계 (담당자 직접 진행)'), (2, '2단계 (인솔파 위임 후보)'), (3, '3단계 (인솔파 직접 위임)'), (4, '기타 (제외·별도 관리)')]),
        ),
    ]
