# Generated by Django 5.0.10 on 2026-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_project_stage_alter_stagetransition_from_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('slate', '회색'), ('orange', '주황'), ('amber', '황색'), ('green', '초록'), ('cyan', '청록'), ('blue', '파랑'), ('purple', '보라'), ('pink', '분홍'), ('red', '빨강')], default='slate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='groups', to='catalog.project')),
            ],
            options={
                'verbose_name': '그룹',
                'verbose_name_plural': '그룹',
                'ordering': ['name'],
            },
        ),
    ]
