# Generated by Django 5.0.10 on 2026-05-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='이 프로젝트가 병합된 메인 프로젝트. 단일 레벨만 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_children', to='catalog.project'),
        ),
    ]
